-- ===================================================================
-- V1 baseline — postgres 프로파일 전용 (pgvector 하이브리드 검색 개발/스테이징/실효성 측정 차량)
-- JPA 엔티티(KnowledgeRecord, SearchLog) + BaseEntity 감사필드를 PostgreSQL 타입으로 미러한다.
-- 이 프로파일은 ddl-auto: none — Hibernate 가 DDL/검증에 관여하지 않고 Flyway 가 스키마를 소유한다.
-- H2(local, create-drop) · Redshift(scripts/redshift) 경로와 무관(Flyway 는 postgres 프로파일에서만 활성).
-- created_at 은 DEFAULT now() — KnowledgeRecord 적재가 JdbcTemplate(JPA Auditing 미경유) 경로이기 때문.
-- ===================================================================

CREATE TABLE knowledge_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain            VARCHAR(100)  NOT NULL,
    title             VARCHAR(500)  NOT NULL,
    body              TEXT          NOT NULL,
    source_url        VARCHAR(1000),
    code_values       JSONB,                       -- 코드값 일치는 jsonb containment(@>) 로 정밀 평가
    source_updated_at TIMESTAMPTZ,
    content_hash      VARCHAR(64)   NOT NULL,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ,
    deleted_at        TIMESTAMPTZ
);

CREATE INDEX idx_knowledge_record_domain ON knowledge_record (domain);
CREATE UNIQUE INDEX uk_knowledge_record_content_hash ON knowledge_record (content_hash);

CREATE TABLE search_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_raw        VARCHAR(2000),
    query_normalized VARCHAR(2000),
    tool             VARCHAR(100),
    latency_ms       BIGINT,
    hit_count        INTEGER,
    judged_score     INTEGER,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ,
    deleted_at       TIMESTAMPTZ
);
