-- ===================================================================
-- V3 — 문서 청크 테이블 (로드맵 #3 청킹, postgres 프로파일 전용)
-- 장문 본문을 문장 청크로 나눠 청크별 임베딩을 저장한다. 벡터 arm 이 문서의 최상(min-거리) 청크로
-- 문서를 랭킹해 통째-임베딩의 희석을 피한다. 청크 적재는 search.chunking.enabled=true 일 때만 수행한다.
-- ===================================================================

CREATE TABLE knowledge_chunk (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id   BIGINT       NOT NULL REFERENCES knowledge_record(id),
    chunk_index INT          NOT NULL,
    content     TEXT         NOT NULL,
    embedding   vector(1024),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_knowledge_chunk_record ON knowledge_chunk (record_id);
CREATE INDEX idx_knowledge_chunk_embedding
    ON knowledge_chunk USING hnsw (embedding vector_cosine_ops);
